# This file relates to internal XMOS infrastructure and should be ignored by users

an_number: an02046
an_number_upper: AN02046
project: '{{an_number}}'
title: '{{an_number_upper}}: Adding CDC Virtual Comm Port to USB Audio'
version: 1.0.0

documentation:
  exclude_patterns_path: doc/exclude-patterns.inc
  root_doc: doc/rst/an02046.rst
  cognidox_part_number: XM-000000-AN
  pdfs:
    doc/rst/an02046.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{an_number}}_v{{version}}'
      pdf_short: yes
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{an_number}}_v{{version}}_readme'
      pdf_short: yes

software:
  cognidox_part_number: XM-000000-SM

